### ISSUE TITLE
Adding Ruby

### ISSUE THREAD

**Issue by ghost** [OperationCode/exercism-io#2]
Following the instructions for adding Ruby via rvm and I got this `-bash: gpg: command not found`

**Comment by ghost** [comment]
Not sure if this helps, but I found my solution on Stackoverflow (http://stackoverflow.com/questions/27041885/how-to-resolve-gpg-command-not-found-error-during-rvm-installation/27042267)

I added this command `brew install gnupg gnupg2`

**Comment by aaron-junot** [comment]
JP,
You should add that line `brew install gnupg gnupg2` into the workstation.md file and submit it as a pull request. Good stuff.
